version: "3.5"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    networks:
      - scalibrary-net
  cassandra:
    image: cassandra
    networks:
      - scalibrary-net
  api:
    build: api/.
    ports:
      -  "7000:7000"
    networks:
      - scalibrary-net
    depends_on:
      - mysql
      - cassandra
    
networks:
  scalibrary-net: