version: "3.5"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    networks:
      - scalibrary-net
  cassandra:
    image: cassandra
    networks:
      - scalibrary-net
  api:
    build: api/.
    ports:
      -  "7000:7000"
    networks:
      - scalibrary-net
      - scalibrary-api-net
    depends_on:
      - mysql
      - cassandra
  web:
    build: web/.
    ports:
      - "5173:80"
    networks:
      - scalibrary-api-net
    depends_on:
      - api
    volumes:
      - web:/app
      - /app/node_modules
    
networks:
  scalibrary-net:
  scalibrary-api-net:

volumes:
  web: